# Generated by Django 5.2 on 2025-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes about how the ticket was resolved', null=True),
        ),
    ]
